-- MySQL Script generated by MySQL Workbench
-- Thu Jun 11 13:24:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `buynroll`.`body`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`body` (
  `PkBody` INT NOT NULL AUTO_INCREMENT,
  `bodyName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PkBody`),
  FULLTEXT INDEX `IDX_8734c90603c032b5231738a0bb` (`bodyName`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`color` (
  `PkColor` INT NOT NULL AUTO_INCREMENT,
  `colorCode` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PkColor`),
  FULLTEXT INDEX `IDX_4c5e2e3621137be6eac8c269aa` (`color`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2332
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`gas_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`gas_type` (
  `PkGasType` INT NOT NULL AUTO_INCREMENT,
  `gasType` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PkGasType`),
  FULLTEXT INDEX `IDX_ba6abe9c7c3f38fbc4e773827c` (`gasType`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`drivetrain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`drivetrain` (
  `PkDrivetrain` INT NOT NULL AUTO_INCREMENT,
  `drivetrainCode` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PkDrivetrain`),
  FULLTEXT INDEX `IDX_82d8a62be1045b10337dba298b` (`drivetrainCode`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`transmission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`transmission` (
  `PkTransmission` INT NOT NULL AUTO_INCREMENT,
  `transmissionName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PkTransmission`),
  FULLTEXT INDEX `IDX_fa84b4856f234c2c8deb437b5d` (`transmissionName`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`manufacturer` (
  `PkManufacturer` INT NOT NULL AUTO_INCREMENT,
  `manufacturerName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`PkManufacturer`),
  FULLTEXT INDEX `IDX_841c7b216a56ad08174dfb996d` (`manufacturerName`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`series` (
  `PkSeries` INT NOT NULL AUTO_INCREMENT,
  `seriesName` VARCHAR(255) NULL DEFAULT NULL,
  `manufacturerPkManufacturer` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PkSeries`),
  INDEX `FK_49da742e4f23190066fb1d0ab5a` (`manufacturerPkManufacturer` ASC) VISIBLE,
  FULLTEXT INDEX `IDX_3a4f68bbccc01c92ddc5e9bd37` (`seriesName`) VISIBLE,
  CONSTRAINT `FK_49da742e4f23190066fb1d0ab5a`
    FOREIGN KEY (`manufacturerPkManufacturer`)
    REFERENCES `buynroll`.`manufacturer` (`PkManufacturer`))
ENGINE = InnoDB
AUTO_INCREMENT = 3566
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`model` (
  `PkModel` INT NOT NULL AUTO_INCREMENT,
  `modelName` VARCHAR(255) NOT NULL,
  `endOfProductionYear` VARCHAR(255) NULL DEFAULT NULL,
  `drivetrainPkDrivetrain` INT NULL DEFAULT NULL,
  `transmissionPkTransmission` INT NULL DEFAULT NULL,
  `gasTypePkGasType` INT NULL DEFAULT NULL,
  `bodyPkBody` INT NULL DEFAULT NULL,
  `seriesPkSeries` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PkModel`),
  UNIQUE INDEX `REL_5d066506ded6d3ac43c9b8d9f1` (`drivetrainPkDrivetrain` ASC) VISIBLE,
  UNIQUE INDEX `REL_72014d757b83889108fe98688b` (`transmissionPkTransmission` ASC) VISIBLE,
  UNIQUE INDEX `REL_0ec0348a3cbe45c0c9e8fedaf0` (`gasTypePkGasType` ASC) VISIBLE,
  UNIQUE INDEX `REL_a31a37e7d2460e04aecc232210` (`bodyPkBody` ASC) VISIBLE,
  INDEX `FK_d0653c985d576eb0f9f4f656bec` (`seriesPkSeries` ASC) VISIBLE,
  FULLTEXT INDEX `IDX_83ee1ee96ca790958291f285f6` (`modelName`) VISIBLE,
  CONSTRAINT `FK_0ec0348a3cbe45c0c9e8fedaf0e`
    FOREIGN KEY (`gasTypePkGasType`)
    REFERENCES `buynroll`.`gas_type` (`PkGasType`),
  CONSTRAINT `FK_5d066506ded6d3ac43c9b8d9f1c`
    FOREIGN KEY (`drivetrainPkDrivetrain`)
    REFERENCES `buynroll`.`drivetrain` (`PkDrivetrain`),
  CONSTRAINT `FK_72014d757b83889108fe98688b3`
    FOREIGN KEY (`transmissionPkTransmission`)
    REFERENCES `buynroll`.`transmission` (`PkTransmission`),
  CONSTRAINT `FK_a31a37e7d2460e04aecc2322100`
    FOREIGN KEY (`bodyPkBody`)
    REFERENCES `buynroll`.`body` (`PkBody`),
  CONSTRAINT `FK_d0653c985d576eb0f9f4f656bec`
    FOREIGN KEY (`seriesPkSeries`)
    REFERENCES `buynroll`.`series` (`PkSeries`))
ENGINE = InnoDB
AUTO_INCREMENT = 27051
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`chassis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`chassis` (
  `PkChassis` INT NOT NULL AUTO_INCREMENT,
  `makeYear` VARCHAR(255) NULL DEFAULT NULL,
  `VIN` VARCHAR(255) NULL DEFAULT NULL,
  `kilometers` VARCHAR(255) NOT NULL DEFAULT '0',
  `vehicleState` ENUM('IZVRSNO', 'UREDNO', 'DOBRO', 'RABLJENO', 'LOSIJE', 'DIJELOVI', 'LOSE', 'KARAMBOLIRAN') NOT NULL DEFAULT 'DOBRO',
  `consumption` INT NULL DEFAULT NULL,
  `colorPkColor` INT NULL DEFAULT NULL,
  `modelPkModel` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PkChassis`),
  UNIQUE INDEX `IDX_8cc0b35910c45b23926adab1b3` (`VIN` ASC) VISIBLE,
  INDEX `FK_280ac315d9ef3f165f7dcab41a7` (`colorPkColor` ASC) VISIBLE,
  INDEX `FK_82e5741e3a4fef0beb7350ef93c` (`modelPkModel` ASC) VISIBLE,
  CONSTRAINT `FK_280ac315d9ef3f165f7dcab41a7`
    FOREIGN KEY (`colorPkColor`)
    REFERENCES `buynroll`.`color` (`PkColor`),
  CONSTRAINT `FK_82e5741e3a4fef0beb7350ef93c`
    FOREIGN KEY (`modelPkModel`)
    REFERENCES `buynroll`.`model` (`PkModel`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `isActive` TINYINT NOT NULL DEFAULT '1',
  `userCode` VARCHAR(36) NOT NULL,
  `createdAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `sellerType` ENUM('PRIVATNA_OSOBA', 'PODUZECE') NOT NULL DEFAULT 'PRIVATNA_OSOBA',
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `IDX_78a916df40e02a9deb1c4b75ed` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`user_vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`user_vehicle` (
  `PkUserVehicle` INT NOT NULL AUTO_INCREMENT,
  `RegistriranDaNe` TINYINT NOT NULL DEFAULT '0',
  `userUserId` INT NOT NULL,
  `chassisPkChassis` INT NOT NULL,
  PRIMARY KEY (`PkUserVehicle`),
  UNIQUE INDEX `REL_8bdaa27cd5084e0a972e6978f1` (`userUserId` ASC) VISIBLE,
  UNIQUE INDEX `REL_0798407f4468967950e7b62732` (`chassisPkChassis` ASC) VISIBLE,
  CONSTRAINT `FK_0798407f4468967950e7b627323`
    FOREIGN KEY (`chassisPkChassis`)
    REFERENCES `buynroll`.`chassis` (`PkChassis`),
  CONSTRAINT `FK_8bdaa27cd5084e0a972e6978f18`
    FOREIGN KEY (`userUserId`)
    REFERENCES `buynroll`.`user` (`userId`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`oglas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`oglas` (
  `PkOglas` INT NOT NULL AUTO_INCREMENT,
  `oglasNaziv` VARCHAR(255) NULL DEFAULT NULL,
  `oglasOpis` VARCHAR(2048) NULL DEFAULT NULL,
  `oglasCreatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `lastModified` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `rating` INT NOT NULL DEFAULT '0',
  `views` INT NOT NULL DEFAULT '0',
  `priceMainCurrency` VARCHAR(255) NOT NULL DEFAULT '0',
  `priceSubCurrency` VARCHAR(255) NOT NULL DEFAULT '0',
  `paymentMethod` ENUM('GOTOVINA', 'KARTICNO', 'NA_RATE', 'ZAMJENA') NOT NULL DEFAULT 'GOTOVINA',
  `autoRadioDefs` TEXT NULL DEFAULT NULL,
  `safety` TEXT NULL DEFAULT NULL,
  `accessories` TEXT NULL DEFAULT NULL,
  `theftSafety` TEXT NULL DEFAULT NULL,
  `airConditioning` TEXT NULL DEFAULT NULL,
  `comfortAccessories` TEXT NULL DEFAULT NULL,
  `vehiclePkUserVehicle` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PkOglas`),
  UNIQUE INDEX `REL_aa0bb31dd6df6b298d80d7a021` (`vehiclePkUserVehicle` ASC) VISIBLE,
  FULLTEXT INDEX `IDX_1b68d06a23264120b5579e06f7` (`oglasNaziv`) VISIBLE,
  FULLTEXT INDEX `IDX_c3f9f5eb5496463131eb1755d5` (`oglasOpis`) VISIBLE,
  CONSTRAINT `FK_aa0bb31dd6df6b298d80d7a0212`
    FOREIGN KEY (`vehiclePkUserVehicle`)
    REFERENCES `buynroll`.`user_vehicle` (`PkUserVehicle`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`photo` (
  `PkPhoto` INT NOT NULL AUTO_INCREMENT,
  `photoTitle` VARCHAR(255) NULL DEFAULT NULL,
  `photoOpis` VARCHAR(255) NULL DEFAULT NULL,
  `photoCreatedAt` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `fieldname` VARCHAR(255) NULL DEFAULT NULL,
  `originalname` VARCHAR(255) NULL DEFAULT NULL,
  `encoding` VARCHAR(255) NULL DEFAULT NULL,
  `mimetype` VARCHAR(255) NULL DEFAULT NULL,
  `destination` VARCHAR(255) NULL DEFAULT NULL,
  `filename` VARCHAR(255) NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `size` VARCHAR(255) NULL DEFAULT NULL,
  `oglasPkOglas` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PkPhoto`),
  INDEX `FK_89d31cca69d23390b04c91a80c9` (`oglasPkOglas` ASC) VISIBLE,
  FULLTEXT INDEX `IDX_756c83eb3cc26d82a56659eeb2` (`photoTitle`) VISIBLE,
  CONSTRAINT `FK_89d31cca69d23390b04c91a80c9`
    FOREIGN KEY (`oglasPkOglas`)
    REFERENCES `buynroll`.`oglas` (`PkOglas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `buynroll`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `buynroll`.`role` (
  `PkRole` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `userUserId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PkRole`),
  INDEX `FK_08c73027e9fbc78a2205a46a698` (`userUserId` ASC) VISIBLE,
  CONSTRAINT `FK_08c73027e9fbc78a2205a46a698`
    FOREIGN KEY (`userUserId`)
    REFERENCES `buynroll`.`user` (`userId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
